# Generated by Django 3.0.3 on 2021-12-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_start', models.IntegerField(default=0)),
                ('pos_end', models.IntegerField(default=0)),
                ('node_uri', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=500)),
                ('original_object_uri', models.CharField(default='', max_length=1000)),
                ('ontology_uri', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.FileField(blank=True, null=True, upload_to='db.File/bytes/filename/mimetype')),
                ('name', models.CharField(default='Не указано', max_length=500)),
                ('original_object_uri', models.CharField(default='', max_length=1000)),
                ('resource_type', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TextRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_entity', to='db.Entity')),
                ('end', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_entity', to='db.Entity')),
                ('markup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_markup', to='db.Markup')),
                ('start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_entity', to='db.Entity')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='markup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_markup', to='db.Markup'),
        ),
    ]
