# Generated by Django 3.0.3 on 2023-05-05 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0002_markup_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ontologies_uris', models.TextField()),
                ('res_ontologies_uris', models.TextField()),
                ('selected_classes_uris', models.TextField()),
                ('res_selected_classes_uris', models.TextField()),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
