# Generated by Django 3.0.3 on 2023-05-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='res_star_classes_uris',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ontologies_uris',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='res_ontologies_uris',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='res_selected_classes_uris',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='selected_classes_uris',
            field=models.TextField(default='[]'),
        ),
    ]
