# Generated by Django 3.0.3 on 2023-05-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20230505_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='original_object_uri',
        ),
        migrations.AddField(
            model_name='resource',
            name='uris',
            field=models.FileField(default='[]', upload_to=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to='db.File/files'),
        ),
    ]
