# Generated by Django 3.0.3 on 2023-05-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20230509_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='ontology_uri',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uris',
            field=models.TextField(default='[]'),
        ),
    ]
