# Generated by Django 3.0.3 on 2023-05-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20230509_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to='db.File/bytes/filename/mimetype'),
        ),
    ]
