# Generated by Django 3.0.3 on 2023-12-09 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20230509_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('layout', models.TextField(default='{}')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='db.Project')),
            ],
        ),
    ]
