# Generated by Django 3.0.3 on 2023-12-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_projectpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='layout',
        ),
        migrations.CreateModel(
            name='ProjectPageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=1)),
                ('y', models.IntegerField(default=1)),
                ('h', models.IntegerField(default=1)),
                ('w', models.IntegerField(default=1)),
                ('page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='db.ProjectPage')),
            ],
        ),
    ]
