# Generated by Django 3.0.3 on 2023-12-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20231209_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpageblock',
            name='data',
            field=models.TextField(default='{}'),
        ),
    ]
