# Generated by Django 3.0.3 on 2023-12-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_projectpageblock_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpageblock',
            name='block_type',
            field=models.TextField(default='text'),
        ),
    ]
