# Generated by Django 3.0.3 on 2023-12-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_projectpageblock_block_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='uris',
        ),
        migrations.AddField(
            model_name='resource',
            name='connected_entity_uri',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='file_uri',
            field=models.TextField(default=''),
        ),
    ]
