# Generated by Django 3.0.3 on 2023-12-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20231215_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEmbedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='[]')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='db.Project')),
            ],
        ),
    ]
