# Generated by Django 3.0.3 on 2023-12-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_projectembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectembedding',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectembedding',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectembedding',
            name='progress',
            field=models.TextField(default=''),
        ),
    ]
