# Generated by Django 3.0.3 on 2023-12-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20231221_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectembedding',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
