# Generated by Django 3.0.3 on 2023-12-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_account_is_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vk_avatar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='vk_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='account',
            name='vk_name',
            field=models.TextField(default=''),
        ),
    ]
